//Authentication Actions 
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

//Reset Password 

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

//Admin

export const GET_ADMIN_SUCCESS = "GET_ADMIN_SUCCESS";
export const GET_ADMIN_FAILURE = "GET_ADMIN_FAILURE";

export const ADD_ADMIN_SUCCESS = "ADD_ADMIN_SUCCESS";
export const ADD_ADMIN_FAILURE = "ADD_ADMIN_FAILURE";

export const EDIT_ADMIN_SUCCESS = "EDIT_ADMIN_SUCCESS";
export const EDIT_ADMIN_FAILURE = "EDIT_ADMIN_FAILURE";

export const DELETE_ADMIN_SUCCESS = "DELETE_ADMIN_SUCCESS";
export const DELETE_ADMIN_FAILURE = "DELETE_ADMIN_FAILURE";

export const RETRIVE_ADMIN_BY_ID_SUCESSS = "RETRIVE_ADMIN_BY_ID_SUCESSS";
export const RETRIVE_BY_ID_FAILURE = "RETRIVE_BY_ID_FAILURE";

export const Act_Deact_Admin_Success = "ACT_DEACT_ADMIN_SUCCESS";
export const Act_Deact_Admin_Failure = "ACT_DEACT_ADMIN_FAILURE";

//profile
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAIL = "EDIT_PROFILE_FAIL";

// Clients 

export const GET_CLIENT_SUCCESS = "GET_CLIENT_SUCCESS";
export const GET_CLIENT_FAILURE = "GET_CLIENT_FAILURE";

export const ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCCESS";
export const ADD_CLIENT_FAILURE = "ADD_CLIENT_FAILURE";

export const EDIT_CLIENT_SUCCESS = "EDIT_CLIENT_SUCCESS";
export const EDIT_CLIENT_FAILURE = "EDIT_CLIENT_FAILURE";

export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";
export const DELETE_CLIENT_FAILURE = "DELETE_CLIENT_FAILURE";

export const Act_Deact_CLIENT_Success = "ACT_DEACT_CLIENT_SUCCESS";
export const Act_Deact_CLIENT_Failure = "ACT_DEACT_CLIENT_FAILURE";

export const RETRIVE_CLIENT_BY_ID_SUCESSS = "RETRIVE_ADMIN_BY_ID_SUCESSS";


// Client Users 

export const GET_CLIENT_USERS_SUCCESS = "GET_CLIENT_USERS_SUCCESS";
export const GET_CLIENT_USERS_FAILURE = "GET_CLIENT_USERS_FAILURE";

export const ADD_CLIENT_USERS_SUCCESS = "ADD_CLIENT_USERS_SUCCESS";
export const ADD_CLIENT_USERS_FAILURE = "ADD_CLIENT_USERS_FAILURE";

export const EDIT_CLIENT_USERS_SUCCESS = "EDIT_CLIENT_USERS_SUCCESS";
export const EDIT_CLIENT_USERS_FAILURE = "EDIT_CLIENT_USERS_FAILURE";

export const DELETE_CLIENT_USERS_SUCCESS = "DELETE_CLIENT_USERS_SUCCESS";
export const DELETE_CLIENT_USERS_FAILURE = "DELETE_CLIENT_USERS_FAILURE";

export const Act_Deact_CLIENT_USERS_Success = "ACT_DEACT_CLIENT_USERS_SUCCESS";
export const Act_Deact_CLIENT_USERS_Failure = "ACT_DEACT_CLIENT_USERS_FAILURE";

export const RETRIVE_CLIENTUSER_BY_ID_SUCESSS = "RETRIVE_ADMIN_BY_ID_SUCESSS";


// Campaigns 

export const GET_CAMPAIGNS_SUCCESS = "GET_CAMPAIGNS_SUCCESS";
export const GET_CAMPAIGNS_FAILURE = "GET_CAMPAIGNS_FAILURE";

export const ADD_CAMPAIGNS_SUCCESS = "ADD_CAMPAIGNS_SUCCESS";
export const ADD_CAMPAIGNS_FAILURE = "ADD_CAMPAIGNS_FAILURE";

export const EDIT_CAMPAIGNS_SUCCESS = "EDIT_CAMPAIGNS_SUCCESS";
export const EDIT_CAMPAIGNS_FAILURE = "EDIT_CAMPAIGNS_FAILURE";

export const DELETE_CAMPAIGNS_SUCCESS = "DELETE_CAMPAIGNS_SUCCESS";
export const DELETE_CAMPAIGNS_FAILURE = "DELETE_CAMPAIGNS_FAILURE";

export const Act_Deact_CAMPAIGNS_Success = "ACT_DEACT_CAMPAIGNS_SUCCESS";
export const Act_Deact_CAMPAIGNS_Failure = "ACT_DEACT_CAMPAIGNS_FAILURE";

export const RETRIVE_CAMPAIGN_BY_ID_SUCESSS = "RETRIVE_ADMIN_BY_ID_SUCESSS";


// leads 

export const GET_ALL_LEADS_SUCCESS = "GET_ALL_LEADS_SUCCESS";
export const GET_ALL_LEADS_FAILURE = "GET_ALL_LEADS_FAILURE";

export const ADD_LEADS_SUCCESS = "ADD_LEADS_SUCCESS";
export const ADD_LEADS_FAILURE = "ADD_LEADS_FAILURE";

export const EDIT_LEADS_SUCCESS = "EDIT_LEADS_SUCCESS";
export const EDIT_LEADS_FAILURE = "EDIT_LEADS_FAILURE";

export const DELETE_LEADS_SUCCESS = "DELETE_LEADS_SUCCESS";
export const DELETE_LEADS_FAILURE = "DELETE_LEADS_FAILURE";

export const IMPORT_LEADS_SUCCESS = "IMPORT_LEADS_SUCCESS";
export const IMPORT_LEADS_FAILURE = "IMPORT_LEADS_FAILURE";

export const RETRIVE_LEADS_BY_ID_SUCESSS = "RETRIVE_ADMIN_BY_ID_SUCESSS";

export const LEADS_STATUS_SUCCESS = "LEADS_STATUS_SUCCESS";

// leads imports 

export const LEADS_IMPORT_SUCCESS = "LEADS_IMPORT_SUCCESS";

// leads notes 

export const LEADS_NOTES_GET_SUCCESS = "LEADS_NOTES_GET_SUCCESS";
export const LEADS_NOTES_UPDATE_SUCCESS = "LEADS_NOTES_UPDATE_SUCCESS";
export const LEADS_NOTES_DELETE_SUCCESS = "LEADS_NOTES_DELETE_SUCCESS";